MetOffice/SimSys_Scripts

kgo_updates/kgo_update/kgo_update.py, kgo_updates/kgo_update/meto_run_kgo_script.sh, kgo_updates/meto_update_kgo.sh
These changes allow the kgo update scripts to work with cylc 7 and cylc8. There are changes to allow the scripts to find variables*.cylc files as well as variables*.rc files and for the wrapper shell scripts to work for lfricinputs kgo installation as well as for UM. 
The first commit is a straight copy of the scripts from the UM trunk.
=> 7 kgo update script

script_copyright_checker/file/UKCA_Cam.regex_template, script_copyright_checker/file/UKCA_cam2.template
This change removes the `UKCA_cam2.template` template and adds an equivalent Regex one that accepts alternative copyright years.
Fixes #17
=> Update UKCA University of Cambridge template to match date regex

nightly_testing/generate_test_suite_cron.py
The adjoint tests builds are failing when launched from a cronjob with the working copy in /tmp. While the actual reason for this is investigated we'll launch from $TMPDIR instead which seems to work. Linked with [LFRic_Apps:#44](https://code.metoffice.gov.uk/trac/lfric_apps/ticket/44)
=> change wc loc

kgo_updates/meto_update_kgo.sh, nightly_testing/generate_test_suite_cron.py, nightly_testing/retrigger_nightlies.py, nightly_testing/tests/test_generate_test_suite_cron.py
A script to automatically relaunch and retrigger suites during meto nightly testing.
This PR also edits the generate script to set lfric apps heads testing to use a new working copy as the heads step edits the working copy. Updates relevant unit test for this.
Linked to MetOffice/simulation-systems#159
=> Add nightly retrigger script

nightly_testing/generate_test_suite_cron.py, nightly_testing/tests/test_generate_test_suite_cron.py
The copy command moving the lfric_apps working copy to a new copy for heads has been failing. This adds a -f flag to stop that and also rearranges where this copy occurs to only do it once per night.
=> Fix heads copy

nightly_testing/example_meto_configs.yaml, nightly_testing/generate_test_suite_cron.py, nightly_testing/retrigger_nightlies.py, nightly_testing/tests/test_generate_test_suite_cron.py
I've had a request from Oliver asking if we're able to do some "next-version" testing of cylc with our rose-stems when it has an initial deploy in the near future. This PR adds that functionality to the nightly testing script. The script has been run with the example yaml file with a suitable example and produces the expected output. Unit tests have been added for the new function.
=> Next cylc nightly

nightly_testing/generate_test_suite_cron.py
In the last change the type returned by get_major_cylc_version was changed during the review process. This equality was missed so the cylc play command for cylc8 suites didn't happen. Have double checked the output of the script now which contains the cylc play commands.
=> modify equality type

suite_report.py
In cylc8 suite_report determines the source URL from the version control file. This URL isn't guaranteed to be the top of a "working copy", so modify suite_report to parse this url such that it is the case.
=> Fix cylc8 source URL

kgo_updates/meto_update_kgo.sh
Last release we hit an error where the new-release flag wasn't exactly specified and so the script wasn't run in new-release mode. This PR adds some checking to ensure that this doesn't happen.
=> add check for unknown command line arguments

script_umdp3_checker/bin/umdp3_check.pl
Currently, UM dependencies are checked by the UMDP3 checker on the trunk.
However, in a branch, the branch diff is used rather than the source files themselves. (This means the script only checks things that are changed by a branch, not the entire source tree.) 
This in turn means changes from the other dependencies are not checked until _after_ they are on trunk in a linked ticket. (This is because the branch diff contains only the changes to the sources, not the code changes themselves - which exist in a different repository.)
This pull request modifies the script to ensure dependencies are checked with the branch, when the script identifies that either the `rose-suite.conf` file, or the `HOST_SOURCE` environment variables have been modified. In that case, it inspects the full source of …
=> UMPD3 checker: Check external repositories when they are modified by a branch.

script_umdp3_checker/bin/umdp3_check.pl
The UMDP3 checker uses a perl feature which assumes that keys() can be called in a scalar context, based on an experimental feature introduced in v5.14 which has now been withdrawn.
This changes the code to use a temporary hash to make the context of the call explict.  This allows the keys() function to be used to generate a list of unique extracted names.
=> Remove retired perl feature from UMDP3 checker

lfric_macros/apply_macros.py, lfric_macros/tests/test_apply_macros.py
For now LFRic Apps has a copy of Jules Shared metadata rather than using the original in Jules. This is required as the build system can't use remote metadata for now.
Therefore there is no point extracting Jules as part of applying upgrade macros. This PR comments out relevant lines in the hope that we can use the Jules copy one day.
=> remove jules from apply_macros script

lfric_macros/apply_macros.py
One request from the reviewer meeting was to have a template docstring to describe what a macro is doing.
At the moment the script removes docstrings from the macros - this was done to aid development of the script, but it would be better practice to not remove them now.
This PR will remove the parsing of docstrings from the script.
=> remove processing of docstrings

suite_report.py
Currently the code section for Fortran files is established by checking the trunk copy of the file.  
NEW files will always report as "unknown code owner" and  MODIFIED files will report whatever is on trunk regardless of any change on the branch. 
This seems backwards so I've reversed it.   
There is a now back up check on the trunk version in case a file has been deleted on the working copy. 
Also updated a comment in `export_file` method which was presumably outdated following a previous change.
=> Switch code section check to working copy rather than trunk

lfric_macros/apply_macros.py
It might be better to write out macros to all versions.py files rather than just the applications versions.py files.
The disadvantages:
* less neat / more duplication of code (though all handled automatically)
* more merge conflicts when committing tickets which need to be handled manually (at least for now)
Advantages:
* when adding a new application  having a definitive versions.py file for all metadata imports would make getting a version branch onto trunk much easier.
* Would avoid issues seen in vn2.0.1 apps release where the linear_model app imported science metadata rather than the applications metadata.
Will raise with the team which option we think is better.
This branch works as expected, having been tested on the vn2.0.1 branch with a macro from LFRic_Apps:#467
=> change apply_macros to print macros to all files, including science

nightly_testing/generate_test_suite_cron.py
We've been asked to run lfric core test suites from the umtest nightly setup. This requires a small edit to the nightly testing script to add lfric as a repo.
=> add core to nightly script

lfric_macros/apply_macros.py, lfric_macros/files/template_versions.py, lfric_macros/release_lfric.py, lfric_macros/tests/test_apply_macros.py
Add a script for completing lfric releases. This script copies metadata, adds and applies a new upgrade macro and then updates the versions.py files. Adding the script to this repo as it uses a lot of functions from apply_macros so makes sense to live in the same location.
A few modifications to allow the apply_macros script to be used during an LFRic release:
* allow main to be called from a different python script by moving command line parsing out of it. Also rename name to apply_macros_main.
* Add option to specify the version as we are dealing with 2 versions when doing a release and reading from the after tag doesn't work.
* Apply isort as well as black to edited files. isort is used to help adding a new import during the release script, so makes sense to keep the versions.py …
=> Add release script for lfric

lfric_macros/apply_macros.py
Linked with [LFRic_Apps:#544](https://code.metoffice.gov.uk/trac/lfric_apps/ticket/544).
Changes required to the apply_macros script once metadata import paths work from a toplevel rose-meta directory. This PR will keep backwards compatibility with previous import commands.
This needs to be committed before [LFRic_Apps:#544](https://code.metoffice.gov.uk/trac/lfric_apps/ticket/544)
=> Central meta changes

kgo_updates/meto_update_kgo.sh
While reviewing the linter ticket I realised that some commands in the kgo scripts were hardcoded to frum instead of using umadmin as they are on azspice. This ticket fixes that.
=> add root_user variable

lfric_macros/release_lfric.py
Formatting of the kgo variables file to remove ticket numbers was missed from the initial release script ticket. This adds it back in.
=> Add variables file formatting to release script

kgo_updates/meto_update_kgo.sh
LFRic Inputs is about to start running on the EX1A so we need to enable the kgo rsync between EX platforms.
I've tested these changes by installing the new inputs kgo with them.
=> enable inputs sync ex's

nightly_testing/generate_test_suite_cron.py, nightly_testing/retrigger_nightlies.py
This makes a couple of minor improvements to the nightly testing scripts:
* Removes any sources left in the lfric_apps dependencies.sh file when doing Heads testing. This means that when the dependencies file update is missed at commit, there will still be valid testing the next night.
* cylc-next testing is only launched if there is a new version of cylc to test. This tests the symlink `cylc-8` and `cylc-next` symlinks and only launches testing if they are not the same.
* Relaunches `cylc-next` tests with the correct environment.
=> small changes to nightly testing scripts

suite_report.py
The only script using `optparse` was `suite_report.py`.  This has been updated to use `argparse` and the script has been linted and its compliance with flake8 improved.
A before and after comparison of the output from `suite_report.py` shows no change in behaviour:
```
vdi> python suite_report.py -S ~/cylc-run/vn13.6_remove_optparse/runN/ -L /var/tmp
svn://fcm1/monc.xm_svn/casim/trunk appears to be the trunk, nothing to do!
svn://fcm1/jules.xm_svn/main/trunk appears to be the trunk, nothing to do!
svn://fcm1/moci.xm_svn/main/trunk appears to be the trunk, nothing to do!
svn://fcm1/um.xm_svn/mule/trunk appears to be the trunk, nothing to do!
svn://fcm1/utils.xm_svn/shumlib/trunk appears to be the trunk, nothing to do!
svn://fcm1/socrates.xm_svn/main/trunk appears to be the trunk, nothing …
```
=> Replace optparse with argparse in suite_report.py

lfric_macros/check_macro_chains.py
The test added yesterday fails on old spice with `SyntaxError: f-string expression part cannot include a backslash`, presumably because it's using an older version of python. I've modified the offending bit of code and checked it works on old spice.
=> Fix macro test old spice

suite_report.py
The physics fork updated the location of the jules and socrates extract paths, so checks in suite report for lfric testing stopped working. This PR fixes that.
I've tested this by running on a Jules rose-stem run with changes to extracted files and made sure lfric testing is requested
=> fix for suite_report extract paths

nightly_testing/generate_test_suite_cron.py
The cylc-8-next symlink was pointing to a later version for the first time last night since I modified the nightly cronjobs to only run when these were different. This has shown a couple of minor issues with this.
=> fix for next-cylc testing

fcm_bdiff.py
With large changesets fcm_bdiff can fill the buffer, causing a hang - this is often seen with a non-appearing trac.log. This ticket adds a timeout to the fcm_bdiff subprocess, preventing the hang. This has been tested on a Apps branch with a large changeset.
Add timeout to fcm_bdiff subprocess command. Also changes from subprocess.popen to subprocess.run which is a nicer interface.
Using subprocess.run with text=True, means fcm_bdiff now requires python3.9.
=> add timeout to fcm_bdiff

suite_report.py
#83 tried to fix issues with including branches in suite report, but this doesn't seem to be working in every case - I suspect the last minute shuffle of indentation of the "else"!
This ticket makes the solution more robust by using "fcm info" to get the branch URL in any situation where the SRS URL hasn't been found another way. This also means that "fcm info" isn't called multiple times per repository which is a more effecient solution. 
Adjusting the logic around the fcm info call.
=> Suite report fix

suite_report.py
The `suite_report.py` script does not currently work on the NG-ARCH sandbox.  This adds support for the platform and its local mirror repository.
These include:
* the addition of empty dictionary entries for the `azngarch` site
* the replacement of the string processing which identifies the repository with a more flexible regexp
None.  Change should be transparent.
Resolves #85
=> Update suite report for azngarch

kgo_updates/meto_update_kgo.sh
The kgo update script will provide a default username of the current user and default platforms of `azpice ex1a` to reduce amount of typing.
=> add default kgo options

script_umdp3_checker/bin/umdp3_check.pl
Fix the svn pattern in UMDP3 checker to deal with repo name changes.
Minor change to the trunk branch pattern.
None
None
* #90 
NA
=> Fix the fcm trunk URL pattern in UMDP3 checker

lfric_macros/apply_macros.py
When a new metadata section with rose app is added, at commit to trunk the app needs to be updated to the latest metadata. This means any imported metadata macros need to be applied to the app and so they need to be copied into the new versions.py by apply_macros. This change adds that functionality.
I've tested this against the new Jules app to ensure it works. I've also checked normal macros work as they currently do. The new functions should get a unit test, but I've not yet added this. I'll open a new issue to add these, and to setup the unit tests to run as CI.
I'm not convinced that the combine_missing_macros function will work perfectly in more complex cases where there are multiple metadata imports. However it is ok for now and will unblock some existing apps tickets.
=> don't copy in versionXX_YY imports

kgo_updates/meto_update_kgo.sh
When running on just azspice, the `ex_kgo_host` variable is undefined which causes the script to fail. This adds the variable as undefined in this case allowing the script to finish
=> fix kgo script

lfric_macros/release_lfric.py
JULES shared metadata doesn't contain any macros (these are handled seperately) so wants excluding from most of the LFRIc Apps release processes. It does still need to have a copy of the HEAD metadata at the release version. 
* Change find_meta_dirs() to be more generic, passing in the exclude list seperately.
* Using find_meta_dirs() to seperately create a set of jules shared metadata directories from the rest and create a combined set of jules shared metadirs and the rest of the metadirs
* Use the combined set for copy_head_meta() only.
=> Update release script to cope with JULES shared metadata

suite_report.py
CodeQL reports overly permissive regex, due to a typo. This change should fix the warning.
=> Fix Overly permissive regular expression range

kgo_updates/meto_update_kgo.sh
This script needs to work for both lfric and UM kgo, so needs to able to work with variables.cylc files and variables.rc files. It works out the extension by looking for either the flow.cylc or suite.rc in the top level rose-stem directory.
Unfortunately the UM was updated to use a flow.cylc, but didn't rename all the files. So it needs .rc extension but has a flow.cylc and so this script has broken. 
Fix temporarily by looking for family-common.rc instead of suite.rc. By vn14.0 it will use all .cylc extensions, so all this logic can be removed.
=> temporary fix for kgo updates

git-migration/config.json, git-migration/ssd_svn2git.sh
We may want to skip a list of repositories from trac -> GitHub sync.  The changes enable this via `--skip=repo1,repo2`  option.
Example in dry-run mode
```bash
$ ./ssd_svn2git.sh -n -m -s mule,shumlib
2025-09-29 23:26:25 Dry run
--------------------------------------------------------------------
gitlify is /path/to/gitlify 
jq is /usr/bin/jq
gh is /usr/bin/gh
--------------------------------------------------------------------
WORKDIR: /path/to/git-migration-work-dir
CONFIG_FILE: /path/to/SimSys_Scripts/git-migration/config.json
UPDATE_GITHUB: 0
--------------------------------------------------------------------
https://metomi/svn/monc.xm/casim ....................... git@github.com:MetOffice/casim
https://metomi/svn/moci.xm/main ........................ git@github.com:MetOffice/moci …
```
=> Skip named repositories from GitHub Sync
